# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:       Geoff Thwaites
email:       grthwaites@hotmail.com
description: Geoff Thwaites is a glass artist, specialising in engraving, based in Cambridge, England.
baseurl:     "" # the subpath of your site, e.g. /blog
url:         "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
#google_analytics: 

collections:
  pages:
    output:    true
    permalink: /:title/
  commission:
    output:    true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout:  default
  - scope:
      path: ""
      type: commission
    values:
      layout:  photo
      gallery: Commission

# Build settings
markdown: kramdown
#theme: minima

plugins:
#  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - jekyll_serve.sh
